[I 2025-04-21 10:21:53.826 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2025-04-21 10:21:53.829 ServerApp] jupyter_server_terminals | extension was successfully linked.
[W 2025-04-21 10:21:53.829 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2025-04-21 10:21:53.829 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2025-04-21 10:21:53.829 LabApp] 'allow_origin' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2025-04-21 10:21:53.829 LabApp] 'base_url' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2025-04-21 10:21:53.831 ServerApp] ServerApp.token config is deprecated in 2.0. Use IdentityProvider.token.
[I 2025-04-21 10:21:53.831 ServerApp] jupyterlab | extension was successfully linked.
[I 2025-04-21 10:21:53.833 ServerApp] notebook | extension was successfully linked.
[I 2025-04-21 10:21:53.834 ServerApp] Writing Jupyter server cookie secret to /root/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2025-04-21 10:21:53.970 ServerApp] notebook_shim | extension was successfully linked.
[W 2025-04-21 10:21:53.980 ServerApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 2025-04-21 10:21:53.980 ServerApp] notebook_shim | extension was successfully loaded.
[I 2025-04-21 10:21:53.981 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2025-04-21 10:21:53.982 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2025-04-21 10:21:53.983 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.10/dist-packages/jupyterlab
[I 2025-04-21 10:21:53.983 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 2025-04-21 10:21:53.984 LabApp] Extension Manager is 'pypi'.
[I 2025-04-21 10:21:54.046 ServerApp] jupyterlab | extension was successfully loaded.
[I 2025-04-21 10:21:54.048 ServerApp] notebook | extension was successfully loaded.
[I 2025-04-21 10:21:54.049 ServerApp] Serving notebooks from local directory: /workspace
[I 2025-04-21 10:21:54.049 ServerApp] Jupyter Server 2.15.0 is running at:
[I 2025-04-21 10:21:54.049 ServerApp] http://test4-0:8888/notebook/s-jain-training-7/test4/lab
[I 2025-04-21 10:21:54.049 ServerApp]     http://127.0.0.1:8888/notebook/s-jain-training-7/test4/lab
[I 2025-04-21 10:21:54.049 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2025-04-21 10:21:54.059 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2025-04-21 10:22:15.709 ServerApp] 302 GET /notebook/s-jain-training-7/test4/ (@127.0.0.6) 0.59ms
[W 2025-04-21 10:22:16.471 LabApp] Could not determine jupyterlab build status without nodejs
[I 2025-04-21 10:23:09.363 ServerApp] New terminal with automatic name: 1
[I 2025-04-21 11:33:41.932 ServerApp] Uploading file to /vid.mp4
[I 2025-04-21 11:33:42.945 ServerApp] Saving file at /vid.mp4
[W 2025-04-21 11:35:44.354 ServerApp] 400 GET /notebook/s-jain-training-7/test4/api/contents/runs/detect/predict/vid.avi?type=file&content=1&hash=1&format=text&contentProviderId=undefined&1745235344139 (127.0.0.6): /workspace/runs/detect/predict/vid.avi is not UTF-8 encoded
[W 2025-04-21 11:35:44.354 ServerApp] wrote error: '/workspace/runs/detect/predict/vid.avi is not UTF-8 encoded'
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/services/contents/fileio.py", line 536, in _read_file
        (bcontent.decode("utf8"), "text", bcontent)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 6: invalid continuation byte
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.10/dist-packages/tornado/web.py", line 1790, in _execute
        result = await result
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/auth/decorator.py", line 73, in inner
        return await out
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/services/contents/handlers.py", line 156, in get
        model = await ensure_async(
      File "/usr/local/lib/python3.10/dist-packages/jupyter_core/utils/__init__.py", line 198, in ensure_async
        result = await obj
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/services/contents/filemanager.py", line 926, in get
        model = await self._file_model(
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/services/contents/filemanager.py", line 835, in _file_model
        content, format, bytes_content = await self._read_file(os_path, format, raw=True)  # type: ignore[misc]
      File "/usr/local/lib/python3.10/dist-packages/jupyter_server/services/contents/fileio.py", line 545, in _read_file
        raise HTTPError(
    tornado.web.HTTPError: HTTP 400: bad format (/workspace/runs/detect/predict/vid.avi is not UTF-8 encoded)
[W 2025-04-21 11:35:44.356 ServerApp] 400 GET /notebook/s-jain-training-7/test4/api/contents/runs/detect/predict/vid.avi?type=file&content=1&hash=1&format=text&contentProviderId=undefined&1745235344139 (9757838f311a410190779a862b41e768@127.0.0.6) 185.83ms referer=http://192.168.1.248:32243/notebook/s-jain-training-7/test4/lab/tree/runs/detect/predict/vid.avi
